### ISSUE TITLE
[feature request] Split a user-supplied secret into shares?

### ISSUE THREAD

**Issue by jonathancross** [posener/sharedsecret#6]
Generally speaking, sss software is used to split a given secret into shares which can then be distributed. AFAICT sharedsecret does not support this, correct?

**Comment by posener** [comment]
That is a good idea.
You are right, currently not supported.
Would you like to contribute?

**Comment by jonathancross** [comment]
Unfortunately I've never worked in `go` and probably would not trust my own implimentation of any cryptography where security is important.

#### How I came upon this project

I've been looking around for a simple tool to do SSS which also could output shares as a mnemonic phrase. This would be very useful to backup private Bitcoin keys, gpg EC keys, passwords, etc. -- "offline" on paper.
